# Generated by Django 3.2.5 on 2021-07-02 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_name', models.TextField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Autogenerated by the post request')),
                ('payment_method', models.CharField(choices=[('CREDIT CARD', 'CREDIT CARD'), ('PAYPAL', 'PAYPAL'), ('BANK TRANSFER', 'BANK TRANSFER')], default='CREDIT CARD', help_text='Choose your payment method', max_length=20)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
