# Generated by Django 3.2.4 on 2021-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("transaction", "0002_alter_transaction_status")]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("FAILED", "FAILED"),
                    ("UNPROCESSED", "UNPROCESSED"),
                    ("WAITING", "WAITING"),
                    ("SUCCESSFUL", "SUCCESSFUL"),
                ],
                default="UNPROCESSED",
                max_length=50,
            ),
        )
    ]
