# Generated by Django 3.2.5 on 2021-07-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_name',
            field=models.CharField(default="User's name", max_length=100),
        ),
    ]
