# Generated by Django 3.2.5 on 2021-07-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='wallet name', max_length=100),
        ),
    ]
