# Generated by Django 3.2.4 on 2021-06-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("farms", "0001_initial")]

    operations = [migrations.RemoveField(model_name="farm", name="price")]
