# Generated by Django 3.2.4 on 2021-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("farms", "0002_remove_farm_price")]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="duration",
            field=models.DurationField(help_text="in years"),
        ),
        migrations.AlterField(
            model_name="farm",
            name="roi",
            field=models.DecimalField(
                decimal_places=5, help_text="in percentage", max_digits=20
            ),
        ),
    ]
