# Generated by Django 3.2.4 on 2021-06-27 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210626_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'FARMER'), ('INVESTOR', 'INVESTOR')], default='INVESTOR', help_text='The options are Farmer and investor', max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(help_text='Account number field.', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(help_text='Address of the farm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(help_text='The banks in Nigeria', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(help_text='Date of birth of the user', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('RATHER NOT SAY', 'RATHER NOT SAY')], default='RATHER NOT SAY', help_text='Gender of the User', max_length=19),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Phone Number of the user', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?234?\\d(8,15)$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('ABIA', 'ABIA'), ('ABUJA', 'ABUJA'), ('ADAMAWA', 'ADAMAWA'), ('AKWA IBOM', 'AKWA IBOM'), ('ANAMBRA', 'ANAMBRA'), ('BAUCHI', 'BAUCHI'), ('BAYELSA', 'BAYELSA'), ('BENUE', 'BENUE'), ('BORNO', 'BORNO'), ('CROSS RIVER', 'CROSS RIVER'), ('DELTA', 'DELTA'), ('EBONYI', 'EBONYI'), ('EDO', 'EDO'), ('EKITI', 'EKITI'), ('ENUGU', 'ENUGU'), ('GOMBE', 'GOMBE'), ('IMO', 'IMO'), ('JIGAWA', 'JIGAWA'), ('KADUNA', 'KADUNA'), ('KANO', 'KANO'), ('KATSINA', 'KATSINA'), ('KEBBI', 'KEBBI'), ('KOGI', 'KOGI'), ('KWARA', 'KWARA'), ('LAGOS', 'LAGOS'), ('NASAWARA', 'NASAWARA'), ('NIGER', 'NIGER'), ('OGUN', 'OGUN'), ('ONDO', 'ONDO'), ('OSUN', 'OSUN'), ('OYO', 'OYO'), ('PLATEAU', 'PLATEAU'), ('RIVERS', 'RIVERS'), ('SOKOTO', 'SOKOTO'), ('TARABA', 'TARABA'), ('YOBE', 'YOBE'), ('ZAMFARA', 'ZAMFARA')], default='ABUJA', help_text='All the states in Nigeria and the FCT', max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Autogenerated by the post request'),
        ),
    ]
