# Generated by Django 3.2.4 on 2021-06-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("User", "0006_remove_user_phone_number")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default=0,
                help_text="Phone Number of the user",
                max_length=16,
                unique=True,
            ),
            preserve_default=False,
        )
    ]
