# Generated by Django 3.2.4 on 2021-07-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("User", "0009_auto_20210704_1221")]

    operations = [
        migrations.RenameField(
            model_name="verification", old_name="is_active", new_name="is_valid"
        )
    ]
