# Generated by Django 3.2.4 on 2021-07-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("User", "0010_rename_is_active_verification_is_valid")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bank_name",
            field=models.CharField(
                blank=True, help_text="The banks in Nigeria", max_length=25, null=True
            ),
        )
    ]
